package com.onboarding.system.enums;

public enum EmployeeStatus
{
    INVITED,
    ACCOUNT_CREATED,

    PROFILE_PENDING,
    PROFILE_COMPLETED,

    EDUCATION_PENDING,
    EDUCATION_COMPLETED,

    EXPERIENCE_PENDING,
    EXPERIENCE_COMPLETED,

    BANK_DETAILS_PENDING,
    BANK_DETAILS_COMPLETED,

    DOCUMENTS_PENDING,
    DOCUMENTS_SUBMITTED,
    DOCUMENTS_REJECTED,
    DOCUMENTS_APPROVED,

    POLICY_PENDING,
    POLICY_ACCEPTED,

    ONBOARDED
}
